### ISSUE TITLE
Broken view on macOS Catalina

### ISSUE THREAD

**Issue by huseyinemanet** [ukn530/FontFinder#14]
Hey, it's a great plugin and I'm using constantly. Yesterday I upgraded to macOS Catalina and it's suddenly turns out like the attachment. Any idea how to fix that?

![Screen Shot 2019-07-28 at 18 12 39](https://user-images.githubusercontent.com/878928/62009086-c36ba080-b163-11e9-9bcd-b9658b6cf42e.png)

**Comment by himynameisubik** [comment]
Feel free to use my fork:
https://github.com/himynameisubik/FontFinder

Also created a pull request: https://github.com/ukn530/FontFinder/pull/15

**Comment by ukn530** [comment]
Thank you! Merged it!
