### ISSUE TITLE
The plugin doesn't work

### ISSUE THREAD

**Issue by lanceplaine** [ukn530/FontFinder#8]
I have Sketch 45.1

The detection of the font works (I can see the list of the fonts) but when I check a font and click on the "Select" button nothing happens

<img width="464" alt="screen shot 2017-07-03 at 4 38 53 pm" src="https://user-images.githubusercontent.com/5476205/27797512-40f60c06-600e-11e7-8660-c14259b2a861.png">

Let me know if I can provide more information

Thanks!

**Comment by afcramalho** [comment]
Same problem. Thanks.

**Comment by bear-r** [comment]
Same issue here as well.

**Comment by ukn530** [comment]
Thanks for telling!
I'll fix it.

**Comment by ukn530** [comment]
@lanceplaine @afcramalho @bear-r 
Now the problem was fixed.
Download [zip](https://github.com/ukn530/FontFinder/archive/master.zip) again! Thanks!

**Comment by lanceplaine** [comment]
@ukn530 

I just downloaded it and tested it.
It's working.

Thanks :)
